//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winston.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserVoucher()
        {
            this.VoucherTransaction = new HashSet<VoucherTransaction>();
        }
    
        public long UserVoucherID { get; set; }
        public string Code { get; set; }
        public long OfferID { get; set; }
        public long VoucherID { get; set; }
        public long UserID { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public bool Valid { get; set; }
    
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherTransaction> VoucherTransaction { get; set; }
    }
}
