//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winston.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.UserVoucher = new HashSet<UserVoucher>();
            this.VoucherTransaction = new HashSet<VoucherTransaction>();
        }
    
        public long VoucherID { get; set; }
        public long OfferID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Images { get; set; }
        public int PointCost { get; set; }
        public int Type { get; set; }
        public int Amount { get; set; }
        public int CalculationType { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<long> KeyAcountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CalculationTypeEnum CalculationTypeEnum { get; set; }
        public virtual KeyAccount KeyAccount { get; set; }
        public virtual Offer Offer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVoucher> UserVoucher { get; set; }
        public virtual VoucherTypeEnum VoucherTypeEnum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherTransaction> VoucherTransaction { get; set; }
    }
}
